%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%DEBUT DE LA FONCTION PRINCIPALE%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function gui_appdata_findobj

% Création de l'objet Figure
figure('units','pixels',...
    'position',[250 250 400 400],...
    'numbertitle','off',...
    'name','[GUI] Utilisation de SETAPPDATA / GETAPPDATA',...
    'menubar','none',...
    'tag','interface');


% Création de l'objet Uicontrol Text résultat
uicontrol('style','edit',...
    'position',[240 355 150 30],...
    'string','0',...
    'tag','nbCouches');

uicontrol('Style','text',...
                'String','Nombre de couches cachées :',...
                'FontSize',12,...
                'Position',[0 350 230 30]);
            
uicontrol('style','edit',...
    'position',[240 290 150 30],...
    'string','0',...
    'tag','nbEpochs');

uicontrol('Style','text',...
                'String','Nombre d''epochs maximal :',...
                'FontSize',12,...
                'Position',[0 285 230 30]);

uicontrol('Style','text',...
        'String','Choisir la répartition Training/Validation/Test :',...
        'FontSize',12,...
        'Position',[0 225 400 30]);
    
    uicontrol('style','edit',...
    'position',[20 190 100 30],...
    'string','0',...
    'tag','TrainingSet');

    uicontrol('style','edit',...
    'position',[155 190 100 30],...
    'string','0',...
    'FontSize',12,...
    'tag','ValidationSet');

    uicontrol('style','edit',...
    'position',[290 190 100 30],...
    'string','0',...
    'FontSize',12,...
    'tag','TestSet');
    
uicontrol('Style', 'pushbutton', 'String', 'Load data',...
        'Position', [30 75 120 40],...
        'FontSize',10,...
        'Callback', 'uiopen(''*.csv'');');    
    
uicontrol('Style','text',...
    'String','Algorithme d''apprentissage : ',...
    'FontSize',12,...
    'Position',[0 130 220 30]);
    
uicontrol('Style', 'popup',...
           'String', {'Levenberg-Marquardt','Bayesian','Scaled Conjugate Gradient'},...
           'FontSize',10,...
           'Position', [220 102 160 60]); 
       
uicontrol('Style', 'pushbutton', 'String', 'Launch training',...
        'Position', [150 20 120 40],...
        'FontSize',10,...
        'Callback', @valider);    
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%FIN DE LA FONCTION PRINCIPALE%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%DEBUT DE LA FONCTION METTRE A JOUR%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function valider(obj,event)
    t = findobj(gcbf,'nbCouches','string');
    x=get(t,'string');
    nbCouches=num2str(x);
    disp(nbCouches);
end



